sudo: false
language: cpp
compiler: g++-5

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - mesa-common-dev
        - g++-5

install:
    - |
        if [ "$CXX" = "g++" ]; then 
            export CXX="g++-5" CC="gcc-5"; 
        fi
    - |
        if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
            CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
            mkdir -p tmp/cmake
            travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C tmp/cmake
            export PATH=tmp/cmake/bin:${PATH}
        fi

before_script:
    - cmake -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-std=c++11" -DCMAKE_INSTALL_PREFIX="$TRAVIS_BUILD_DIR/Install" -B./Build -H./
    
script:    
    - cmake --build ./Build --target all
    
after_script:
    - cmake --build ./Build --target package

deploy:
    provider: releases
    api_key: "ada3ad1ee68bd8bc9d94f08c3824ca7f00472f06"
    file: $TRAVIS_BUILD_DIR/build/app/CodeTestApp
    skip_cleanup: true
    on:
        tags: true
