env:
  global:
    - CMAKE_URL="https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz"
    - CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/Install"
    - CXX_FLAGS="-std=c++11"

matrix:
  include:
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
              - ubuntu-toolchain-r-test
          packages:
              - mesa-common-dev
              - g++-5
      env:
         - ENV_CMAKE_OPTIONS="-DPLATFORM_NAME=Linux-x86"
         - ENV_CXX_FLAGS="-m32"
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
              - ubuntu-toolchain-r-test
          packages:
              - mesa-common-dev
              - g++-5
              - g++-5-multilib
      env:
        - ENV_CMAKE_OPTIONS="-DPLATFORM_NAME=Linux-x64"
        - ENV_CXX_FLAGS="-m64"

cache:
  ccache: true
  directories:
    - ${TRAVIS_BUILD_DIR}/tmp/cmake
    - ${TRAVIS_BUILD_DIR}/Build/Extern/Source/Docopt

install:
  - |
    if [ "$CXX" = "g++" ]; then 
      export CXX="g++-5" CC="gcc-5"; 
    fi
  - |
    if [ ! -f "${TRAVIS_BUILD_DIR}/tmp/cmake/cached" ]; then
      mkdir -p ${TRAVIS_BUILD_DIR}/tmp/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/tmp/cmake          
      touch ${TRAVIS_BUILD_DIR}/tmp/cmake/cached
    fi
    export PATH=${TRAVIS_BUILD_DIR}/tmp/cmake/bin:${PATH}
  - |
    export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

before_script:
  - cmake -G "Unix Makefiles" ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -B./Build -H./
    
script:    
  - cmake --build ./Build --target all
    
after_script:
  - cmake --build ./Build --target package

deploy:
  provider: releases
  api_key: "ada3ad1ee68bd8bc9d94f08c3824ca7f00472f06"
  file: $TRAVIS_BUILD_DIR/build/app/CodeTestApp
  skip_cleanup: true
  on:
    tags: true
